version: '3'
services:
  mongodb:
    container_name: database_mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: cajamarcap
      MONGO_INITDB_ROOT_PASSWORD: 2002pamelak
 
  webapi:
    container_name: netcore_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mongodb
    environment:
      ConnectionStrings__MongoDB: "mongodb+srv://cajamarcap:2002pamelak@cluster0.k2uggj5.mongodb.net/?retryWrites=true&w=majority"